//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateCookies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produced
    {
        public System.DateTime PTime { get; set; }
        public string PName { get; set; }
        public string PPallet { get; set; }
        public int ProductPNumber { get; set; }
        public int OrderONumber { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
