//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateCookies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RQuantity { get; set; }
        public int IngredientINumber { get; set; }
        public int ProductPNumber { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Product Product { get; set; }
    }
}
