//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uppgift2ConsoleApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNumber {
            get {
                return this.CNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CNumberField, value) != true)) {
                    this.CNumberField = value;
                    this.RaisePropertyChanged("CNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CName {
            get {
                return this.CNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNameField, value) != true)) {
                    this.CNameField = value;
                    this.RaisePropertyChanged("CName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CAddress {
            get {
                return this.CAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CAddressField, value) != true)) {
                    this.CAddressField = value;
                    this.RaisePropertyChanged("CAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CPostalAddress {
            get {
                return this.CPostalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CPostalAddressField, value) != true)) {
                    this.CPostalAddressField = value;
                    this.RaisePropertyChanged("CPostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CCountry {
            get {
                return this.CCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CCountryField, value) != true)) {
                    this.CCountryField = value;
                    this.RaisePropertyChanged("CCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CEmail {
            get {
                return this.CEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CEmailField, value) != true)) {
                    this.CEmailField = value;
                    this.RaisePropertyChanged("CEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ReadCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadCustomer", ReplyAction="*")]
        Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponse ReadCustomer(Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponse> ReadCustomerAsync(Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCustomer", Namespace="http://tempuri.org/", Order=0)]
        public Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequestBody Body;
        
        public ReadCustomerRequest() {
        }
        
        public ReadCustomerRequest(Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadCustomerRequestBody {
        
        public ReadCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponseBody Body;
        
        public ReadCustomerResponse() {
        }
        
        public ReadCustomerResponse(Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Uppgift2ConsoleApplication.ServiceReference1.Customer> ReadCustomerResult;
        
        public ReadCustomerResponseBody() {
        }
        
        public ReadCustomerResponseBody(System.Collections.Generic.List<Uppgift2ConsoleApplication.ServiceReference1.Customer> ReadCustomerResult) {
            this.ReadCustomerResult = ReadCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap>, Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponse Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap.ReadCustomer(Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest request) {
            return base.Channel.ReadCustomer(request);
        }
        
        public System.Collections.Generic.List<Uppgift2ConsoleApplication.ServiceReference1.Customer> ReadCustomer() {
            Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest inValue = new Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest();
            inValue.Body = new Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequestBody();
            Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponse retVal = ((Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap)(this)).ReadCustomer(inValue);
            return retVal.Body.ReadCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponse> Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap.ReadCustomerAsync(Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest request) {
            return base.Channel.ReadCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerResponse> ReadCustomerAsync() {
            Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest inValue = new Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequest();
            inValue.Body = new Uppgift2ConsoleApplication.ServiceReference1.ReadCustomerRequestBody();
            return ((Uppgift2ConsoleApplication.ServiceReference1.WebServiceSoap)(this)).ReadCustomerAsync(inValue);
        }
    }
}
