//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavWindowApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmployeeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Employee_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Middle_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Job_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Search_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Post_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mobile_PhoneNo_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Alt__Address_CodeField;
        
        private System.DateTime Alt__Address_Start_DateField;
        
        private System.DateTime Alt__Address_End_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        private System.DateTime Birth_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Social_Security_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Union_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Union_Membership_No_Field;
        
        private int SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Country_Region_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Manager_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emplymt__Contract_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Statistics_Group_CodeField;
        
        private System.DateTime Employment_DateField;
        
        private int StatusField;
        
        private System.DateTime Inactive_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cause_of_Inactivity_CodeField;
        
        private System.DateTime Termination_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Grounds_for_Term__CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Global_Dimension_1_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Global_Dimension_2_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Resource_No_Field;
        
        private System.DateTime Last_Date_ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fax_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Company_E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Salespers__Purch__CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No__SeriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((object.ReferenceEquals(this.timestampField, value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Employee_No_ {
            get {
                return this.Employee_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Employee_No_Field, value) != true)) {
                    this.Employee_No_Field = value;
                    this.RaisePropertyChanged("Employee_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Middle_Name {
            get {
                return this.Middle_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Middle_NameField, value) != true)) {
                    this.Middle_NameField = value;
                    this.RaisePropertyChanged("Middle_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Job_Title {
            get {
                return this.Job_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Job_TitleField, value) != true)) {
                    this.Job_TitleField = value;
                    this.RaisePropertyChanged("Job_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Search_Name {
            get {
                return this.Search_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Search_NameField, value) != true)) {
                    this.Search_NameField = value;
                    this.RaisePropertyChanged("Search_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Address_2 {
            get {
                return this.Address_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address_2Field, value) != true)) {
                    this.Address_2Field = value;
                    this.RaisePropertyChanged("Address_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Post_Code {
            get {
                return this.Post_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Post_CodeField, value) != true)) {
                    this.Post_CodeField = value;
                    this.RaisePropertyChanged("Post_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Phone_No_ {
            get {
                return this.Phone_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_No_Field, value) != true)) {
                    this.Phone_No_Field = value;
                    this.RaisePropertyChanged("Phone_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Mobile_PhoneNo_ {
            get {
                return this.Mobile_PhoneNo_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Mobile_PhoneNo_Field, value) != true)) {
                    this.Mobile_PhoneNo_Field = value;
                    this.RaisePropertyChanged("Mobile_PhoneNo_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Alt__Address_Code {
            get {
                return this.Alt__Address_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Alt__Address_CodeField, value) != true)) {
                    this.Alt__Address_CodeField = value;
                    this.RaisePropertyChanged("Alt__Address_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime Alt__Address_Start_Date {
            get {
                return this.Alt__Address_Start_DateField;
            }
            set {
                if ((this.Alt__Address_Start_DateField.Equals(value) != true)) {
                    this.Alt__Address_Start_DateField = value;
                    this.RaisePropertyChanged("Alt__Address_Start_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.DateTime Alt__Address_End_Date {
            get {
                return this.Alt__Address_End_DateField;
            }
            set {
                if ((this.Alt__Address_End_DateField.Equals(value) != true)) {
                    this.Alt__Address_End_DateField = value;
                    this.RaisePropertyChanged("Alt__Address_End_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.DateTime Birth_Date {
            get {
                return this.Birth_DateField;
            }
            set {
                if ((this.Birth_DateField.Equals(value) != true)) {
                    this.Birth_DateField = value;
                    this.RaisePropertyChanged("Birth_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Social_Security_No_ {
            get {
                return this.Social_Security_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Social_Security_No_Field, value) != true)) {
                    this.Social_Security_No_Field = value;
                    this.RaisePropertyChanged("Social_Security_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Union_Code {
            get {
                return this.Union_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Union_CodeField, value) != true)) {
                    this.Union_CodeField = value;
                    this.RaisePropertyChanged("Union_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Union_Membership_No_ {
            get {
                return this.Union_Membership_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Union_Membership_No_Field, value) != true)) {
                    this.Union_Membership_No_Field = value;
                    this.RaisePropertyChanged("Union_Membership_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Country_Region_Code {
            get {
                return this.Country_Region_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Country_Region_CodeField, value) != true)) {
                    this.Country_Region_CodeField = value;
                    this.RaisePropertyChanged("Country_Region_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Manager_No_ {
            get {
                return this.Manager_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Manager_No_Field, value) != true)) {
                    this.Manager_No_Field = value;
                    this.RaisePropertyChanged("Manager_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string Emplymt__Contract_Code {
            get {
                return this.Emplymt__Contract_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Emplymt__Contract_CodeField, value) != true)) {
                    this.Emplymt__Contract_CodeField = value;
                    this.RaisePropertyChanged("Emplymt__Contract_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Statistics_Group_Code {
            get {
                return this.Statistics_Group_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Statistics_Group_CodeField, value) != true)) {
                    this.Statistics_Group_CodeField = value;
                    this.RaisePropertyChanged("Statistics_Group_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.DateTime Employment_Date {
            get {
                return this.Employment_DateField;
            }
            set {
                if ((this.Employment_DateField.Equals(value) != true)) {
                    this.Employment_DateField = value;
                    this.RaisePropertyChanged("Employment_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public System.DateTime Inactive_Date {
            get {
                return this.Inactive_DateField;
            }
            set {
                if ((this.Inactive_DateField.Equals(value) != true)) {
                    this.Inactive_DateField = value;
                    this.RaisePropertyChanged("Inactive_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string Cause_of_Inactivity_Code {
            get {
                return this.Cause_of_Inactivity_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cause_of_Inactivity_CodeField, value) != true)) {
                    this.Cause_of_Inactivity_CodeField = value;
                    this.RaisePropertyChanged("Cause_of_Inactivity_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public System.DateTime Termination_Date {
            get {
                return this.Termination_DateField;
            }
            set {
                if ((this.Termination_DateField.Equals(value) != true)) {
                    this.Termination_DateField = value;
                    this.RaisePropertyChanged("Termination_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string Grounds_for_Term__Code {
            get {
                return this.Grounds_for_Term__CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Grounds_for_Term__CodeField, value) != true)) {
                    this.Grounds_for_Term__CodeField = value;
                    this.RaisePropertyChanged("Grounds_for_Term__Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string Global_Dimension_1_Code {
            get {
                return this.Global_Dimension_1_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Global_Dimension_1_CodeField, value) != true)) {
                    this.Global_Dimension_1_CodeField = value;
                    this.RaisePropertyChanged("Global_Dimension_1_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string Global_Dimension_2_Code {
            get {
                return this.Global_Dimension_2_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Global_Dimension_2_CodeField, value) != true)) {
                    this.Global_Dimension_2_CodeField = value;
                    this.RaisePropertyChanged("Global_Dimension_2_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string Resource_No_ {
            get {
                return this.Resource_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Resource_No_Field, value) != true)) {
                    this.Resource_No_Field = value;
                    this.RaisePropertyChanged("Resource_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.Last_Date_ModifiedField;
            }
            set {
                if ((this.Last_Date_ModifiedField.Equals(value) != true)) {
                    this.Last_Date_ModifiedField = value;
                    this.RaisePropertyChanged("Last_Date_Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string Pager {
            get {
                return this.PagerField;
            }
            set {
                if ((object.ReferenceEquals(this.PagerField, value) != true)) {
                    this.PagerField = value;
                    this.RaisePropertyChanged("Pager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string Fax_No_ {
            get {
                return this.Fax_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fax_No_Field, value) != true)) {
                    this.Fax_No_Field = value;
                    this.RaisePropertyChanged("Fax_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string Company_E_Mail {
            get {
                return this.Company_E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.Company_E_MailField, value) != true)) {
                    this.Company_E_MailField = value;
                    this.RaisePropertyChanged("Company_E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string Salespers__Purch__Code {
            get {
                return this.Salespers__Purch__CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Salespers__Purch__CodeField, value) != true)) {
                    this.Salespers__Purch__CodeField = value;
                    this.RaisePropertyChanged("Salespers__Purch__Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string No__Series {
            get {
                return this.No__SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.No__SeriesField, value) != true)) {
                    this.No__SeriesField = value;
                    this.RaisePropertyChanged("No__Series");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        NavWindowApp.ServiceReference1.GetEmployeesResponse GetEmployees(NavWindowApp.ServiceReference1.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.GetEmployeesResponse> GetEmployeesAsync(NavWindowApp.ServiceReference1.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name ShowAllEmployeesListDALResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllEmployeesListDAL", ReplyAction="*")]
        NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponse ShowAllEmployeesListDAL(NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllEmployeesListDAL", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponse> ShowAllEmployeesListDALAsync(NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesList", ReplyAction="*")]
        NavWindowApp.ServiceReference1.GetEmployeesListResponse GetEmployeesList(NavWindowApp.ServiceReference1.GetEmployeesListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeesList", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.GetEmployeesListResponse> GetEmployeesListAsync(NavWindowApp.ServiceReference1.GetEmployeesListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public NavWindowApp.ServiceReference1.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(NavWindowApp.ServiceReference1.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavWindowApp.ServiceReference1.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(NavWindowApp.ServiceReference1.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavWindowApp.ServiceReference1.ArrayOfString GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(NavWindowApp.ServiceReference1.ArrayOfString GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllEmployeesListDALRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllEmployeesListDAL", Namespace="http://tempuri.org/", Order=0)]
        public NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequestBody Body;
        
        public ShowAllEmployeesListDALRequest() {
        }
        
        public ShowAllEmployeesListDALRequest(NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowAllEmployeesListDALRequestBody {
        
        public ShowAllEmployeesListDALRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllEmployeesListDALResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllEmployeesListDALResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponseBody Body;
        
        public ShowAllEmployeesListDALResponse() {
        }
        
        public ShowAllEmployeesListDALResponse(NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowAllEmployeesListDALResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavWindowApp.ServiceReference1.EmployeeModel[] ShowAllEmployeesListDALResult;
        
        public ShowAllEmployeesListDALResponseBody() {
        }
        
        public ShowAllEmployeesListDALResponseBody(NavWindowApp.ServiceReference1.EmployeeModel[] ShowAllEmployeesListDALResult) {
            this.ShowAllEmployeesListDALResult = ShowAllEmployeesListDALResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesList", Namespace="http://tempuri.org/", Order=0)]
        public NavWindowApp.ServiceReference1.GetEmployeesListRequestBody Body;
        
        public GetEmployeesListRequest() {
        }
        
        public GetEmployeesListRequest(NavWindowApp.ServiceReference1.GetEmployeesListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesListRequestBody {
        
        public GetEmployeesListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesListResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavWindowApp.ServiceReference1.GetEmployeesListResponseBody Body;
        
        public GetEmployeesListResponse() {
        }
        
        public GetEmployeesListResponse(NavWindowApp.ServiceReference1.GetEmployeesListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavWindowApp.ServiceReference1.ArrayOfString[] GetEmployeesListResult;
        
        public GetEmployeesListResponseBody() {
        }
        
        public GetEmployeesListResponseBody(NavWindowApp.ServiceReference1.ArrayOfString[] GetEmployeesListResult) {
            this.GetEmployeesListResult = GetEmployeesListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : NavWindowApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<NavWindowApp.ServiceReference1.WebService1Soap>, NavWindowApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWindowApp.ServiceReference1.GetEmployeesResponse NavWindowApp.ServiceReference1.WebService1Soap.GetEmployees(NavWindowApp.ServiceReference1.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public NavWindowApp.ServiceReference1.ArrayOfString GetEmployees() {
            NavWindowApp.ServiceReference1.GetEmployeesRequest inValue = new NavWindowApp.ServiceReference1.GetEmployeesRequest();
            inValue.Body = new NavWindowApp.ServiceReference1.GetEmployeesRequestBody();
            NavWindowApp.ServiceReference1.GetEmployeesResponse retVal = ((NavWindowApp.ServiceReference1.WebService1Soap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.GetEmployeesResponse> NavWindowApp.ServiceReference1.WebService1Soap.GetEmployeesAsync(NavWindowApp.ServiceReference1.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.GetEmployeesResponse> GetEmployeesAsync() {
            NavWindowApp.ServiceReference1.GetEmployeesRequest inValue = new NavWindowApp.ServiceReference1.GetEmployeesRequest();
            inValue.Body = new NavWindowApp.ServiceReference1.GetEmployeesRequestBody();
            return ((NavWindowApp.ServiceReference1.WebService1Soap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponse NavWindowApp.ServiceReference1.WebService1Soap.ShowAllEmployeesListDAL(NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest request) {
            return base.Channel.ShowAllEmployeesListDAL(request);
        }
        
        public NavWindowApp.ServiceReference1.EmployeeModel[] ShowAllEmployeesListDAL() {
            NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest inValue = new NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest();
            inValue.Body = new NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequestBody();
            NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponse retVal = ((NavWindowApp.ServiceReference1.WebService1Soap)(this)).ShowAllEmployeesListDAL(inValue);
            return retVal.Body.ShowAllEmployeesListDALResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponse> NavWindowApp.ServiceReference1.WebService1Soap.ShowAllEmployeesListDALAsync(NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest request) {
            return base.Channel.ShowAllEmployeesListDALAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.ShowAllEmployeesListDALResponse> ShowAllEmployeesListDALAsync() {
            NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest inValue = new NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequest();
            inValue.Body = new NavWindowApp.ServiceReference1.ShowAllEmployeesListDALRequestBody();
            return ((NavWindowApp.ServiceReference1.WebService1Soap)(this)).ShowAllEmployeesListDALAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWindowApp.ServiceReference1.GetEmployeesListResponse NavWindowApp.ServiceReference1.WebService1Soap.GetEmployeesList(NavWindowApp.ServiceReference1.GetEmployeesListRequest request) {
            return base.Channel.GetEmployeesList(request);
        }
        
        public NavWindowApp.ServiceReference1.ArrayOfString[] GetEmployeesList() {
            NavWindowApp.ServiceReference1.GetEmployeesListRequest inValue = new NavWindowApp.ServiceReference1.GetEmployeesListRequest();
            inValue.Body = new NavWindowApp.ServiceReference1.GetEmployeesListRequestBody();
            NavWindowApp.ServiceReference1.GetEmployeesListResponse retVal = ((NavWindowApp.ServiceReference1.WebService1Soap)(this)).GetEmployeesList(inValue);
            return retVal.Body.GetEmployeesListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.GetEmployeesListResponse> NavWindowApp.ServiceReference1.WebService1Soap.GetEmployeesListAsync(NavWindowApp.ServiceReference1.GetEmployeesListRequest request) {
            return base.Channel.GetEmployeesListAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWindowApp.ServiceReference1.GetEmployeesListResponse> GetEmployeesListAsync() {
            NavWindowApp.ServiceReference1.GetEmployeesListRequest inValue = new NavWindowApp.ServiceReference1.GetEmployeesListRequest();
            inValue.Body = new NavWindowApp.ServiceReference1.GetEmployeesListRequestBody();
            return ((NavWindowApp.ServiceReference1.WebService1Soap)(this)).GetEmployeesListAsync(inValue);
        }
    }
}
